require("babel-runtime/regenerator")
require("webpack-hot-middleware/client??path=http://localhost:8080/__webpack_hmr&timeout=20000&reload=true")
require("./main.css")
require("./images/link.jpg")
require("./index.html")
require("./app")
